package wolf.games.mobile.tabmaker;

public enum EditorActions {
	DO_NOTHING, EDITOR, INSERT, INSERT_READY, SELECT, SELECT_STARTED, SELECT_READY, DOTS, MOVE, PLAY, PLAY_SELECTION, ZOOMED_OUT, INSERT_READY_WAITING, SELECT_READY_WAITING
}